#!/bin/zsh

# Define the base directory for all terminal plugins and tools
export PLUGIN_DIR="$HOME/repos/terminal/plugins"

# Define the Oh My Zsh custom directory path
export OH_MY_ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"

# Ensure the plugin and Oh My Zsh custom directories exist
mkdir -p "$PLUGIN_DIR"
mkdir -p "$OH_MY_ZSH_CUSTOM/plugins"  # Ensure the custom plugins directory exists

# Install zsh
/bin/bash bin/zsh

# Install Oh My Zsh
/bin/bash bin/oh-my-zsh

# Install diff-so-fancy
/bin/zsh bin/diff-so-fancy

# Install bat
/bin/zsh bin/bat

# Install zsh-bat
/bin/zsh bin/zsh-bat

# Install zsh-autosuggestions
/bin/zsh bin/zsh-autosuggestions

# Install eza
/bin/zsh bin/eza

# Install web-search
/bin/zsh bin/web-search

# Install json-tools
/bin/zsh bin/json-tools


echo "\e[32m✨ All tools and plugins installed successfully. ✨\e[0m"

# Re-source ~/.zshrc to apply changes, if Zsh is now the default shell
if [ "$SHELL" = "$(which zsh)" ]; then
    echo -e "\033[33m🛠 Re-sourcing ~/.zshrc to apply changes... 🛠\033[0m"
    /bin/zsh -c 'source ~/.zshrc'
    echo -e "\033[32m✨ Your terminal environment has been updated. ✨\033[0m"
else
    echo -e "\033[31m❗️ Please change your default shell to Zsh and restart your terminal. ❗️\033[0m"
fi