name: Test Setup Terminal Script

on: [push, pull_request]

jobs:
  test-linux:
    name: Run setup-terminal script on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup-terminal script
        run: |
          chmod +x ./setup-terminal
          ./setup-terminal
        shell: zsh {0}

      - name: Display .zshrc content
        run: cat ~/.zshrc
        shell: zsh {0}
    
  test-macos:
    name: Run setup-terminal script on macOS
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup-terminal script
        run: |
          chmod +x ./setup-terminal
          ./setup-terminal
        shell: zsh {0}

      - name: Display .zshrc content
        run: cat ~/.zshrc
        shell: zsh {0}